개발자 약관 추가
koreanbots/api-docs pull request #11
Opened 2021-06-03 12:22 UTC by wonderlandpark

2021-06-03 12:24 UTC, kijk2869 requested changes

2021-06-03 12:24 UTC, kijk2869 commented on docs/약관.md
> +- 등...
명확하지 않음

2021-06-03 12:28 UTC, wonderlandpark commented on docs/약관.md
> +- 등...
예시

2021-06-04 01:01 UTC, zero734kr approved these changes

2021-06-06 07:00 UTC, zero734kr commented
LGTM

2021-06-06 07:01 UTC, merged